# Generated by Django 4.1.2 on 2022-10-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauser',
            old_name='password1',
            new_name='password',
        ),
    ]
